######**IMPORTANDO BIBLIOTECAS**

In [7]:
import numpy as np # el np es un alias de la biblioteca numpy
import sys # este paquete maneja funciones de sistema

#### **Creando una lista de 10 elementos**

In [8]:
lista1 = list(range(1,11))
lista1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

#### **Consultando el tipo de dato**

In [9]:
type(lista1)

list

#### **Transformando una lista a un Array**
Recordar que "array" es una estructura propia de la libreria numpy

In [10]:
arreglo = np.array(lista1)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### Consultando el tipo de dato númerico del arreglo

In [11]:
arreglo.dtype

dtype('int64')

#### Crear una lista de solo números unos

In [12]:
unos = np.ones(10)
unos

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### **Creando lista de números ceros**

In [13]:
ceros = np.zeros(10)
ceros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### **Lista de datos compuestos (Transformando a Array)**

In [14]:
lista2 = ['Álvaro', 2, 5.6, True]
lista2

['Álvaro', 2, 5.6, True]

#### **Transformando lista mixta en Array**

In [15]:
arreglo2 = np.array(lista2)
arreglo2

array(['Álvaro', '2', '5.6', 'True'], dtype='<U32')

#### **Consultando la cantidad de memoria ocupada por estructura (Paquete Sys)**

In [16]:
memoria_lista = sys.getsizeof(lista1)
memoria_arreglo = arreglo.nbytes

print(f"Memoria ocupada por la lista: {memoria_lista} bytes")
print(f"Memoria ocupada por el arreglo {memoria_arreglo} bytes")

Memoria ocupada por la lista: 136 bytes
Memoria ocupada por el arreglo 80 bytes


#### **Otros métodos de Numpy**

In [17]:
print("Shape:",                  arreglo.shape)     # Dimensiones
print("Dimensiones:",            arreglo.ndim)      # Números de ejes
print("Tamaño:",                 arreglo.size)      # Total de elementos
print("Tipo de dato:",           arreglo.dtype)     # Tipo almacenado
print("Bytes/elem:",             arreglo.itemsize)  # Tamaño de bytes de cada elemento

Shape: (10,)
Dimensiones: 1
Tamaño: 10
Tipo de dato: int64
Bytes/elem: 8


#### **Obteniendo promedio del Arreglo**

In [18]:
promedio = np.mean(lista1)
promedio

np.float64(5.5)

#### **Tranformando el Arreglo de Int a Float**

El método astype() transforma los elementos del arreglo a un tipo determinado de dato númerico

In [19]:
new_arreglo = arreglo.astype(np.float32)
new_arreglo

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

In [20]:
new_arreglo.dtype

dtype('float32')

#### **Aplicando el Paquete Random**

In [21]:
np.random.rand() # Genera números aleatorios del rango [0,1]

0.8207691745942609

In [22]:
np.random.rand(5) # Genera números aleatorios (n cantidad)

array([0.01630435, 0.78995615, 0.78797841, 0.60174549, 0.38829587])

In [23]:
np.random.rand(1,10,4)

array([[[0.59801011, 0.80892118, 0.32936554, 0.14902403],
        [0.22400029, 0.0853213 , 0.72114029, 0.62190505],
        [0.55728916, 0.60040745, 0.78093695, 0.09985305],
        [0.38875068, 0.83454229, 0.51170345, 0.59769856],
        [0.33827436, 0.20141395, 0.58408604, 0.49210834],
        [0.76713246, 0.66586122, 0.99325831, 0.35681991],
        [0.7428623 , 0.54652627, 0.27252303, 0.72689792],
        [0.35409682, 0.48909136, 0.80859479, 0.56877199],
        [0.71965409, 0.60794627, 0.22980182, 0.93746363],
        [0.67428783, 0.73906523, 0.62892303, 0.05064918]]])

In [24]:
np.random.randint(1, 100, 10) # Generando números enteros aleatorios del 1 al 100

array([21, 68, 45, 62, 81, 89, 15, 90, 75, 69])

#### **Método arange**

In [25]:
arreglo_3 = np.arange(1,11)
arreglo_3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
matriz2 = np.random.randint(1,101,(10,10))
matriz2

array([[ 81,  71,  57,  73,  44, 100,  85,  45,  39,   8],
       [ 13,  21,  28,  15,  65,  61,  44,  93,  42,  54],
       [ 20,  30,   1,  87,  73,  90,  15,  60,  86,  59],
       [ 20,  67,  13,  44,  16,  77,  22,  69,  67,  58],
       [ 93,  46,  82,  58,  52,  45,  42,  54,  61,  69],
       [  7,  76,  43,  88,  90,  37,  67,  61,  18,  15],
       [ 81,  49,  22,  17,  95,  53,  89,  85,  84,  32],
       [ 18,  50,  65,   7,  44,  26,  92,  90,  67,  22],
       [  3,  88,  27,  44,  65,  67,  96,  37,  32,  65],
       [ 71,  86,   6,  99,  78,  71,  95,  23,  37,  47]])